### ISSUE TITLE
Morph a Task into an expanded Sub-Process

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#247]

**Comment by gimbel** [comment]
related to #223

**Comment by nikku** [comment]
Should be fixed with latest release?

**Comment by falko** [comment]
I just tried it on the staging system and it is still not possible to morph from a Task into an expanded Sub-Process.

During a modelling session it might become apparent that a Task actually consists of more than one step. In that case it would be very helpful to use morphing rather then deleting the Task with all its connections and Boundary Events.

The way back from Sub-Process to Task could be supported as well. The contents of the Sub-Process would have to be deleted.

**Comment by nikku** [comment]
All right, renamed and reopened the issue.

**Comment by falko** [comment]
Thank you!

**Comment by gimbel** [comment]
> The way back from Sub-Process to Task could be supported as well. The contents of the Sub-Process would have to be deleted.

Since it is debatable if the contents should be deleted, we will leave the "way back from sub-process to task" out of the scope of this issue.

**Comment by gimbel** [comment]
I created a separate issue #510
