### ISSUE TITLE
Context pad disappears while morphing connected element

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#554]
To reproduce:
- Create gateway or task
- Connect to a task
- Morph to another element
- Undo

Result: no context pad available anymore.

![context-pad](https://cloud.githubusercontent.com/assets/2331533/15504429/3e5f73e4-21bf-11e6-879f-92d5101d0473.gif)

**Comment by romansmirnov** [comment]
fixed with https://github.com/bpmn-io/diagram-js/issues/170

**Comment by philippfromme** [comment]
Closed with https://github.com/bpmn-io/diagram-js/commit/7f453115caead2ca389fbfc98362880e1e5128b7

**Comment by tohagan** [comment]
Still seeing this bug in Chrome extension (v0.12.0). Does it need to be updated?

**Comment by nikku** [comment]
Chrome extension is likely to not receive updates anymore.

Reason: Google decided to remove extensions so this extension will be obsolete, soon.

**Comment by nikku** [comment]
I personally advice you to switch to a tool such as [Camunda Modeler](https://camunda.org/bpmn/tool/) that does the same, just as a desktop application.
