### ISSUE TITLE
modeling can break completely during connection label auto-adjustment

### ISSUE THREAD

**Issue by vpanfilov** [bpmn-io/bpmn-js#669]
Hello. I have text labels on all connection in my BPMN diagrams. Sometimes during editing I run into seriuos bug, which breaks all interaction with the diagram. This bug can appear randomly when moving connection segments, bendpoints or tasks with incoming/outgoing connections).

I haven't found a reliable way to reproduce this bug yet. It arises randomly in label adjustment stage after connection waypoints are changed. Here is the stacktrace:
```
Error: expected between [1, 2] circle -> line intersections
    at getAttachment (LineAttachmentUtil.js:88) [angular]
    at getLabelAdjustment (LabelLayoutUtil.js:111) [angular]
    at getVisibleLabelAdjustment (LabelBehavior.js:127) [angular]
    at :8000/main.bundle.js:113557:25 [angular]
    at invokeFunction (EventBus.js:455) [angular]
    at EventBus._invokeListener (EventBus.js:354) [angular]
    at EventBus._invokeListeners (EventBus.js:342) [angular]
    at EventBus.fire (EventBus.js:302) [angular]
    at CommandStack._fire (CommandStack.js:344) [angular]
    at CommandStack._internalExecute (CommandStack.js:412) [angular]
    at CommandStack.execute (CommandStack.js:147) [angular]
    at Modeling.layoutConnection (Modeling.js:181) [angular]
    at :8000/main.bundle.js:79727:16 [angular]
    at :8000/main.bundle.js:146391:11 [angular]
    at baseForOwn (baseForOwn.js:14) [angular]
    at :8000/main.bundle.js:146352:14 [angular]
    at :8000/main.bundle.js:146508:9 [angular]
```

I think that it is the result of some floating point calculations error in **getCircleSegmentIntersections** function in **bpmn-js/lib/features/modeling/behavior/util/LineAttachmentUtil.js**. Here are some example values causing this error:
![intersection-error](https://cloud.githubusercontent.com/assets/11993879/23511285/a1bf5de6-ff6d-11e6-9a73-d62145f706a1.png)

**Comment by nikku** [comment]
Since when can you reproduce this issue? Which version of bpmn-js do you use?

**Comment by vpanfilov** [comment]
I am using v0.19 right now with some custom modules (they don't affect coordinates of diagram elements).

But I also reproduced this bug on your demo site today after some time randomly moving shapes and connection around:
![intersection-error2](https://cloud.githubusercontent.com/assets/11993879/23540911/2b3912a6-fff5-11e6-8c1c-b215ee5f4f3a.png)

**Comment by vpanfilov** [comment]
Function `getAttachment` (**bpmn-js/lib/features/modeling/behavior/util/LineAttachmentUtil.js**) returns the attachment position of label to connection. It can be either a bendpoint (label is moving with the given bendpoint) or segment point (label is moving with the given point on a connection segment). It depends on the number of intersections returned by `getCircleSegmentIntersections` function.

This function first calculates minimal distance between label midpoint and segment points (last argument **cr** is redundant). After that it computes the number of intersections of connection segment and a circle (centered on the label midpoint with the radius of minimal distance calculated before).

The bug appears randomly when it should be one intersection point (disc===0). Maybe some epsilon value is needed to be indroduced to mitigate floating point precision errors?
And it definately should be better error handling in the `getAttachment` function. It just throws a "expected between [1, 2] circle -> line intersections" error breaking all modeling operations. Nothing can be edited after that.

**Comment by nikku** [comment]
Agreed that we need better error handling here.

We'll try to reproduce this.

**Comment by vpanfilov** [comment]
It seems that this issue has lots in common with https://github.com/bpmn-io/bpmn-js/issues/595.

**Comment by nikku** [comment]
Do you experience the issues when being zoomed in / out, too?

**Comment by vpanfilov** [comment]
Hi, @nikku ! Here is the example script to reproduce this bug:

```html
<html>
  <head>
    <script src="https://cdn.rawgit.com/bpmn-io/bower-bpmn-js/v0.19.0/dist/bpmn-modeler.js"></script>
    <link rel="stylesheet" href="https://cdn.rawgit.com/bpmn-io/diagram-js/master/assets/diagram-js.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/bpmn-io/bpmn-js/master/assets/bpmn-font/css/bpmn-embedded.css" />
  </head>

  <body>
    <button id="btn" onclick="ReproduceBug()">Reproduce bug</button>
    <div id="canvas" class="canvas" style="width: 100%, height: 90%"></div>
  </body>
  <script>
    var modeler = new BpmnJS({container: '#canvas'});
    modeler.createDiagram();

    var elementRegistry = modeler.get('elementRegistry'),
        elementFactory = modeler.get('elementFactory'),
        bpmnFactory = modeler.get('bpmnFactory'),
        modeling = modeler.get('modeling'),
        canvas = modeler.get('canvas');

    var shape1 = CreateTask(),
        shape2 = CreateTask(),
        shape3 = CreateTask(),
        shape4 = CreateTask(),
        shape5 = CreateTask();

    var counter = 0;


    setTimeout(function() {
      var root = canvas.getRootElement();

      modeling.createShape(shape1, {x: 500, y: 50}, root);
      modeling.createShape(shape2, {x: 500, y: 300}, root);
      modeling.createShape(shape3, {x: 500, y: 550}, root);
      modeling.createShape(shape4, {x: 100, y: 300}, root);
      modeling.createShape(shape5, {x: 1000, y: 300}, root);

      var connection1 = modeling.connect(shape1, shape2);
      modeling.updateLabel(connection1, 'Example label 1');
      var connection2 = modeling.connect(shape2, shape3);
      modeling.updateLabel(connection2, 'Example label');
      var connection3 = modeling.connect(shape2, shape4);
      modeling.updateLabel(connection3, 'Example label');
      var connection4 = modeling.connect(shape2, shape5);
      modeling.updateLabel(connection4, 'Example label');
    });

    function CreateTask() {
      return elementFactory.create('shape', {
        type: 'bpmn:Task'
      });
    }
		
		
    function ReproduceBug() {
      document.getElementById('btn').disabled = true;
      moveShapes();
    }

    function moveShapes() {
      var dx = Math.round(Math.random() * 20 - 10),
          dy = Math.round(Math.random() * 20 - 10);

      modeling.moveShape(shape2, {x: dx, y: dy}, false);

      counter += 1;
      console.log(counter);

      sleep(25, moveShapes);
    }

    function sleep(ms, callback){
      setTimeout(function(){callback();}, ms);
    }
  </script>
</html>
```

As you can see, no zoom or floating point coordinates are required to cause this bug. This code can sometimes rise another bug (In the same `getLabelAdjustment` function), when connection is shrinked to the single point:

```
TypeError: Cannot read property 'segmentIndex' of undefined
    at getLabelAdjustment (LabelLayoutUtil.js:112)
    at getVisibleLabelAdjustment (LabelBehavior.js:127)
    at LabelBehavior.js:147
```

Hope this will be fixed soon, because it is a serious issue.

**Comment by vpanfilov** [comment]
Were you able to reproduce this issue with my simulation script?
Bug is still present in version 0.20.3.

**Comment by nikku** [comment]
Yes, we were able to reproduce at least two issues. Thanks for the comprehensive test case.

**Comment by nikku** [comment]
I've fixed one bug I could reliably reproduce with your test case.

**Comment by vpanfilov** [comment]
Hi! Thanks for fixing zero-length lines bug, but ***expected between [1, 2] circle -> line intersections*** error is still triggering for me sometimes. @nikku had agreed that better error handling is needed in **getAttachment** function in *LineAttachmentUtil.js* (see posts from March 3).
In that function all connection segments are analyzed in a loop to determine closest label attachment (segment start, end or center). Due to floating point precision errors **getCircleSegmentIntersections** can return no intersections for particular segment throwing this error.

Please, reopen this bug.

**Comment by nikku** [comment]
Any browser you can reproduce your issue in?

**Comment by vpanfilov** [comment]
I can reproduce it in all major browsers using my simulation test case (with bpmn-js version bumped to **0.20.5**):
* Yandex Browser (based on Chromium);
![ya2](https://cloud.githubusercontent.com/assets/11993879/25375832/bc682cc4-29aa-11e7-9746-760334ec0b66.png)
![ya3](https://cloud.githubusercontent.com/assets/11993879/25375845/caf4f06a-29aa-11e7-874e-0e3f6ba3229c.png)
* IE 11;
* Firefox;


It seems to me that Chrome is more prone to this bug but it can be my subjective experience.

**Comment by nikku** [comment]
As you said: This must be floating point arithmetic related.

We'll have a look, when time permits. Thank you!

**Comment by philippfromme** [comment]
As you can see in your first screenshot, `x` and `y` of the `cc` are rounded to 3 decimal places.

![unbenannt](https://cloud.githubusercontent.com/assets/7633572/25488995/d5d76d2c-2b68-11e7-9ae1-8563ab2c4c52.png)

I took the exact values and was able to reproduce the error in `getCircleSegmentIntersection`. The bug doesn't occur if all `x` and `y` values are rounded to no decimal places. I wasn't able to reproduce the bug with your test case but I think the error shouldn't occur anymore.

**Comment by nikku** [comment]
That doesn't do it for me on Chrome:

```
77c00c5f0957c4a7d7b33039d8683905.browserify:23556 Error: expected between [1, 2] circle -> line intersections
    at getAttachment (77c00c5f0957c4a7d7b33039d8683905.browserify:8273)
    at getLabelAdjustment (77c00c5f0957c4a7d7b33039d8683905.browserify:8076)
    at getVisibleLabelAdjustment (77c00c5f0957c4a7d7b33039d8683905.browserify:6838)
    at 77c00c5f0957c4a7d7b33039d8683905.browserify:6858
    at invokeFunction (77c00c5f0957c4a7d7b33039d8683905.browserify:23642)
    at EventBus._invokeListener (77c00c5f0957c4a7d7b33039d8683905.browserify:23541)
    at EventBus._invokeListeners (77c00c5f0957c4a7d7b33039d8683905.browserify:23529)
    at EventBus.fire (77c00c5f0957c4a7d7b33039d8683905.browserify:23489)
    at CommandStack._fire (77c00c5f0957c4a7d7b33039d8683905.browserify:21783)
    at CommandStack._internalExecute (77c00c5f0957c4a7d7b33039d8683905.browserify:21851)
```

**Comment by nikku** [comment]
So in summary: With these changes, stuff reliably fails on Chrome.

**Comment by nikku** [comment]
This change does work for me though (very stable on both Chrome and Firefox:

```diff
--- a/lib/features/modeling/behavior/util/LineAttachmentUtil.js
+++ b/lib/features/modeling/behavior/util/LineAttachmentUtil.js
@@ -212,7 +212,7 @@ function mid(p1, p2) {
 }

 function round(n) {
-  return Math.round(n * 1000) / 1000;
+  return Math.round(n * 100000000) / 100000000;
 }

 function roundPoint(p) {
```

**Comment by nikku** [comment]
Nah, still failing. Let's discuss what we do about this tomorrow.

**Comment by vpanfilov** [comment]
I propose to try the following strategy:

1. Introduce a threshold value (something like 1e-8) to **getCircleSegmentIntersections** algorithm of comparing *disc* value with zero;
2. The current behavior of **getAttachment** function is to throw error if **any** of the connection segments fails with this bug. This should be changed to throwing an error only if **all** segments fail with computing intersections. Failing segments should be ignored and not participate in determining closest attachment.
3. Impact of rounding points coordinates on bug probability seems counter-intuitive on the first sight. Maybe it will be better to disable rounding at all and use only threshold value?

**Comment by nikku** [comment]
Rounding is necessary to work around some floating point precision errors in the computation, i.e. sometimes we'd get `disc: -4e-15` values on Chrome without rounding.

In most places it is not necessary; even worse, it adds a lot of unnecessary noise to the computations. 

I think I've implemented something stable as part of https://github.com/bpmn-io/bpmn-js/commit/36c79459b01be5a2af54d97f11fbbca748699270. 

@vpanfilov If you got a moment, try to verify if that fixes the issue for you on your browsers.

**Comment by vpanfilov** [comment]
It's only 6 hours left for me to sleep. I will test this at work tomorrow morning. Thanks for your effort.

**Comment by vpanfilov** [comment]
Code in branch https://github.com/bpmn-io/bpmn-js/tree/669-no-rounding is MUCH more stable for me (and faster). But I catched this bug again after setting a more aggressive moving strategy (without rounding) in my test case:
```js
var dx = Math.random() * 400 - 200,
    dy = Math.random() * 400 - 200;
modeling.moveShape(shape2, {x: dx, y: dy}, false);
```

![after-fix1](https://cloud.githubusercontent.com/assets/11993879/25519467/9aef5b64-2c00-11e7-9aab-34fc1d7ba95a.png)

I had a breakpoint on `return [];` statement in **getCircleSegmentIntersections** but it haven't triggered. So it seems to me that it returns empty array in this block of code:
```js
// return only points on line segment
return [ i1, i2 ].filter(function(p) {
  return isPointInSegment(p, s1, s2);
});
```
But now it's VERY rare, can't catch it again for now. I will try to provide the input values causing this.

**Comment by vpanfilov** [comment]
Catched it (without last https://github.com/bpmn-io/bpmn-js/commit/38fc0f843d365d15c2136c8c8011f9f589693bba commit):

![after-fix2](https://cloud.githubusercontent.com/assets/11993879/25520397/6d943e06-2c04-11e7-9d42-6f0a1b08e027.png)

**Comment by nikku** [comment]
Try latest commit on [669-no-rounding branch](https://github.com/bpmn-io/bpmn-js/compare/669-no-rounding) which should address floating point handling, too.

**Comment by nikku** [comment]
Works stable as a charm for me on Chrome and Firefox using your floating point test case (part of `ModelerSpec.js`):

```javascript
  it.only('should run test-case', function(done) {

    var cvs = document.createElement('div');
    var btn = document.createElement('button');
    btn.textContent = 'START TEST';

    document.body.appendChild(cvs);
    document.body.appendChild(btn);
    cvs.style.position = 'fixed';
    cvs.style.top = 0;
    cvs.style.left = 0;
    cvs.style.bottom = 0;
    cvs.style.right = 0;

    btn.style.position = 'fixed';
    btn.style.top = '5px';
    btn.style.left = '5px';
    btn.onclick = ReproduceBug;

    var modeler = new Modeler({ container: cvs });
    modeler.createDiagram();

    var elementFactory = modeler.get('elementFactory'),
        modeling = modeler.get('modeling'),
        canvas = modeler.get('canvas');

    var shape1 = CreateTask(),
        shape2 = CreateTask(),
        shape3 = CreateTask(),
        shape4 = CreateTask(),
        shape5 = CreateTask();

    var counter = 0;


    setTimeout(function() {
      var root = canvas.getRootElement();

      modeling.createShape(shape1, {x: 500, y: 50}, root);
      modeling.createShape(shape2, {x: 500, y: 300}, root);
      modeling.createShape(shape3, {x: 500, y: 550}, root);
      modeling.createShape(shape4, {x: 100, y: 300}, root);
      modeling.createShape(shape5, {x: 1000, y: 300}, root);

      var connection1 = modeling.connect(shape1, shape2);
      modeling.updateLabel(connection1, 'Example label 1');
      var connection2 = modeling.connect(shape2, shape3);
      modeling.updateLabel(connection2, 'Example label 2');
      var connection3 = modeling.connect(shape2, shape4);
      modeling.updateLabel(connection3, 'Example label 3');
      var connection4 = modeling.connect(shape2, shape5);
      modeling.updateLabel(connection4, 'Example label 4');

      done();
    });

    function CreateTask() {
      return elementFactory.create('shape', {
        type: 'bpmn:Task'
      });
    }


    function ReproduceBug() {
      btn.disabled = true;
      moveShapes();
    }

    function moveShapes() {
      var dx = Math.random() * 40 - 20,
          dy = Math.random() * 40 - 20;
      modeling.moveShape(shape2, {x: dx, y: dy}, false);

      counter += 1;
      console.log(counter);

      sleep(1, moveShapes);
    }

    function sleep(ms, callback){
      setTimeout(function(){callback();}, ms);
    }


  });

```

**Comment by nikku** [comment]
From my perspective, stuff seems to be fixed.

**Comment by nikku** [comment]
@philippfromme Please review the changes.

**Comment by vpanfilov** [comment]
I can more or less reliably reproduce this new ***NaN*** bug if I restart my simulation process every 100 iterations:

```html
<html>
  <head>
    <script src="./bpmn-modeler (2).js"></script>
    <link rel="stylesheet" href="https://cdn.rawgit.com/bpmn-io/diagram-js/master/assets/diagram-js.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/bpmn-io/bpmn-js/master/assets/bpmn-font/css/bpmn-embedded.css" />
  </head>

  <body>
    <button id="btn" onclick="ReproduceBug()">Reproduce bug</button>
    <div id="canvas" class="canvas" style="width: 100%, height: 90%"></div>
  </body>
  <script>
	var modeler = new BpmnJS({container: '#canvas'});
	var elementFactory = modeler.get('elementFactory'),
        modeling = modeler.get('modeling'),
        canvas = modeler.get('canvas');
	var counter;
	var shape1, shape2, shape3, shape4, shape5;
	
	function StartSimulation () {
		
		modeler.createDiagram();

		shape1 = CreateTask();
		shape2 = CreateTask();
		shape3 = CreateTask();
		shape4 = CreateTask();
		shape5 = CreateTask();

		counter = 0;

		setTimeout(function() {
		  var root = canvas.getRootElement();

		  modeling.createShape(shape1, {x: 500, y: 50}, root);
		  modeling.createShape(shape2, {x: 500, y: 300}, root);
		  modeling.createShape(shape3, {x: 500, y: 550}, root);
		  modeling.createShape(shape4, {x: 100, y: 300}, root);
		  modeling.createShape(shape5, {x: 1000, y: 300}, root);

		  var connection1 = modeling.connect(shape1, shape2);
		  modeling.updateLabel(connection1, 'Example label 1');
		  var connection2 = modeling.connect(shape2, shape3);
		  modeling.updateLabel(connection2, 'Example label 2');
		  var connection3 = modeling.connect(shape2, shape4);
		  modeling.updateLabel(connection3, 'Example label 3');
		  var connection4 = modeling.connect(shape2, shape5);
		  modeling.updateLabel(connection4, 'Example label 4');
		  
		  moveShapes();
		});
	}

    function CreateTask() {
      return elementFactory.create('shape', {
        type: 'bpmn:Task'
      });
    }
		
    function ReproduceBug() {
      document.getElementById('btn').disabled = true;
      StartSimulation ();
    }

    function moveShapes() {
		var dx = Math.random() * 100 - 50,
		    dy = Math.random() * 100 - 50;

		modeling.moveShape(shape2, {x: dx, y: dy}, false);

		counter += 1;
		console.log(counter);

		if (counter === 100) {
			StartSimulation ();
		} else {
			sleep(1, moveShapes);
		}
    }

    function sleep(ms, callback){
		setTimeout(function(){callback();}, ms);
    }
  </script>
</html>
```

**Comment by vpanfilov** [comment]
Bug still triggered when I enabled rounding of `dx` and `dy` values. :wink:

**Comment by nikku** [comment]
Fixed the last bug.

**Comment by vpanfilov** [comment]
Label attachment algorythm seems very stable for me now. :+1:  Thank you.

**Comment by nikku** [comment]
Thank you, too for getting me there :wink:.

**Comment by nikku** [comment]
Released with bpmn-js 0.20.6

**Comment by vpanfilov** [comment]
@nikku @philippfromme Big thanks for fixing this issue. I updated bpmn-js version in my app yesterday and will write here if I encounter anything new regarding this bug.
